// ─────────────────────────────────────────────────────────────────
// CivroDA — Centralised Copy & Terminology
// Approval Risk Intelligence Platform
// ─────────────────────────────────────────────────────────────────

export const BRAND = {
  name: "CivroDA",
  category: "Approval Risk Intelligence Platform",
  tagline: "Predict your DA approval risk before you lodge.",
  url: "https://civroda.com",
} as const;

// ── Disclaimers ──────────────────────────────────────────────────
export const DISCLAIMER = {
  short:
    "Decision-support only. Always confirm with a qualified planner.",
  standard:
    "CivroDA provides decision-support insights only and does not constitute planning, legal, or financial advice.",
  pdf: "DISCLAIMER: This report is generated by CivroDA for decision-support purposes only. It does not constitute planning, legal, or financial advice, nor official council documentation. For official determination records, please contact the relevant council directly. Data shown is derived from publicly available development application records.",
} as const;

// ── Meta / SEO ───────────────────────────────────────────────────
export const META = {
  home: {
    title: "CivroDA — Approval Risk Intelligence for Development Applications",
    description:
      "Predict your DA approval risk before you lodge. Precedent-based risk profiles from real council decisions across NSW.",
    og: {
      title: "CivroDA — Approval Risk Intelligence Platform",
      description:
        "Precedent-based risk profiles from real council decisions. Predict approval probability, identify risk drivers, and review council behaviour patterns.",
    },
  },
  search: {
    title: "Run Approval Risk Scan — Development Applications",
    description:
      "Scan development applications across Parramatta, Blacktown & Hornsby. Analyse approval risk, precedent matches, and consent conditions.",
    og: {
      title: "Run Approval Risk Scan | CivroDA",
      description:
        "Scan development applications across Parramatta, Blacktown & Hornsby. Analyse approval risk, precedent matches, and consent conditions.",
    },
  },
  manifest: {
    name: "CivroDA — Approval Risk Intelligence",
    short_name: "CivroDA",
    description:
      "Predict your DA approval risk before you lodge. Precedent intelligence built from real council decisions.",
  },
} as const;

// ── Homepage ─────────────────────────────────────────────────────
export const HOME = {
  hero: {
    eyebrow: (councilCount: number) =>
      `Precedent data from ${councilCount} NSW councils`,
    headline: "Predict Your DA Approval Risk",
    headlineAccent: "Before You Lodge",
    subheadline:
      "Precedent-based risk profiles from real council decisions — starting with NSW and expanding.",
    ctaPrimary: "Run an Approval Risk Scan",
    ctaSecondary: "View Sample Analysis",
  },
  heroStats: {
    coverage: "NSW Councils Covered",
    approvalRate: "Avg. Approval Rate",
    precedents: "Precedent Records",
    signals: "Risk Signals Tracked",
  },
  trustBar: [
    "Active coverage: Parramatta, Blacktown, Hornsby (NSW)",
    "Built for developers, planners, and lenders",
    "NSW expansion underway",
  ],
  howItWorks: {
    label: "How It Works",
    title: "From precedent data to risk intelligence",
    subtitle:
      "We index real council decisions, analyse approval patterns and variation sensitivity, and deliver an actionable risk profile before you lodge.",
    steps: [
      {
        step: "01",
        title: "Ingest precedent data",
        description:
          "We index applications, controls, outcomes, conditions, and refusal reasoning from Parramatta, Blacktown, and Hornsby councils.",
      },
      {
        step: "02",
        title: "Analyse risk patterns",
        description:
          "We compare your proposal against similar approvals and refusals in the same precinct, detecting variation sensitivity and refusal themes.",
      },
      {
        step: "03",
        title: "Deliver a risk profile",
        description:
          "You receive an approval risk summary with indicative probability, key risk drivers, and comparable precedents — before lodgement.",
      },
    ],
  },
  liveData: {
    label: "Platform Intelligence",
    title: "Grounded in real council decisions",
    subtitle:
      "Every metric is computed from actual development application records across covered councils. No modelled estimates.",
  },
  councilCoverage: {
    label: "Council Coverage",
    title: "Active coverage by council area",
    subtitle:
      "Review approval rates, common refusal themes, and typical consent conditions for each local government area.",
  },
  features: {
    eyebrow: "Built for developers & planners",
    title: "De-risk your next DA submission with precedent intelligence",
    description:
      "Whether you are a property developer, town planner, or lender, CivroDA turns weeks of council research into a structured risk profile you can act on.",
    items: [
      {
        title: "Comparable Precedents Nearby",
        description:
          "Identify comparable approvals and refusals matched by zoning, FSR, height, and land size within the same council area.",
      },
      {
        title: "Consent Conditions (Summarised)",
        description:
          "Common consent conditions summarised in plain English — no legal jargon, no ambiguity.",
      },
      {
        title: "Approval Risk Score",
        description:
          "An indicative score based on how similar precedents performed in the same council area.",
      },
      {
        title: "Determination Reports",
        description:
          "Download risk analysis reports with full DA details, conditions, and comparable precedent data.",
      },
    ],
  },
  cta: {
    title: "Understand your approval risk — before you lodge",
    description:
      "Scan development applications across covered councils. Identify risk drivers, review comparable precedents, and reduce planning uncertainty.",
    ctaPrimary: "Run an Approval Risk Scan",
    ctaSecondary: "View Sample Analysis",
  },
  footer: {
    brand:
      "Approval risk intelligence for Australian property development. Precedent analysis, risk profiling, and council behaviour insights.",
    copyright: (year: number) =>
      `\u00A9 ${year} CivroDA. All rights reserved. Data sourced from publicly available council records.`,
    product: {
      title: "Platform",
      links: [
        { href: "/", label: "Overview" },
        { href: "/das", label: "Risk Scan" },
        { href: "/#how-it-works", label: "How It Works" },
      ],
    },
    councils: {
      title: "Councils",
      links: [
        { href: "/councils/parramatta", label: "Parramatta" },
        { href: "/councils/blacktown", label: "Blacktown" },
        { href: "/councils/hornsby", label: "Hornsby" },
      ],
    },
    resources: {
      title: "Resources",
      links: [
        { href: "/das?outcome=Approved", label: "Approved Precedents" },
        { href: "/das?outcome=Refused", label: "Refused Precedents" },
      ],
    },
  },
} as const;

// ── Search / Dashboard ───────────────────────────────────────────
export const SEARCH = {
  title: "Approval Risk Scan",
  subtitle:
    "Filter by council, zoning, and determination outcome across Parramatta, Blacktown & Hornsby",
  resultCount: (total: number) =>
    `${total} development application${total !== 1 ? "s" : ""}`,
  loading: "Scanning precedents\u2026",
  empty: {
    title: "No matching precedents found",
    description:
      "Adjust your filters to broaden the search across covered councils.",
  },
  filters: {
    label: "Risk Scan Filters",
    council: { label: "Council", placeholder: "All Councils" },
    zoning: { label: "Zoning", placeholder: "All Zones" },
    outcome: { label: "Determination", placeholder: "All Outcomes" },
    clearAll: "Clear all",
  },
} as const;

// ── DA Detail ────────────────────────────────────────────────────
export const DA_DETAIL = {
  breadcrumb: "Risk Scan",
  downloadReport: "Download Risk Report",
  downloadReportShort: "PDF",
  metrics: {
    zoning: "Zoning",
    landSize: "Land Size",
    height: "Height",
    fsr: "FSR",
  },
  conditions: {
    approved: "Consent Conditions",
    refused: "Refusal Reasons",
    assessment: "Assessment Conditions",
    helper: "Summarised in plain English",
    empty: "No conditions recorded for this application.",
  },
  similarProjects: {
    title: "Comparable Precedents",
    subtitle: (count: number, council: string) =>
      `${count} comparable DA${count !== 1 ? "s" : ""} in ${council}`,
    empty: "No comparable precedents found in this council area.",
  },
  approvalScore: {
    title: "Approval Risk Score",
    subtitle: (count: number) =>
      `Based on ${count} comparable precedent${count !== 1 ? "s" : ""}`,
  },
  documents: {
    title: "Documents",
    empty: "No documents linked yet.",
  },
} as const;

// ── Risk Meter ───────────────────────────────────────────────────
export const RISK_METER = {
  title: "Approval Risk Profile",
  subtitle: "Indicative Score",
  levels: {
    low: { label: "Low Risk", description: "Strong precedent from similar approved projects in this council area." },
    moderate: { label: "Moderate Risk", description: "Mixed signals from comparable developments — review conditions carefully." },
    high: { label: "High Risk", description: "Similar projects have predominantly been refused in this area." },
  },
  riskDriversTitle: "Key Risk Drivers",
  comparableLink: "View Comparable Precedents",
  indicativeLabel: "Indicative",
} as const;

// ── Council Pages ────────────────────────────────────────────────
export const COUNCIL = {
  councils: {
    parramatta: {
      name: "Parramatta",
      region: "Western Sydney",
      description:
        "Parramatta is one of Sydney\u2019s fastest-growing CBDs with major high-density development. Review approval risk patterns, consent conditions, and refusal themes across residential, commercial, and mixed-use applications in the Parramatta LGA.",
    },
    blacktown: {
      name: "Blacktown",
      region: "Western Sydney",
      description:
        "Blacktown LGA covers a large area of Western Sydney with significant greenfield and infill development. Analyse DA outcomes, council behaviour patterns, and typical consent conditions for projects ranging from single dwellings to industrial warehouses.",
    },
    hornsby: {
      name: "Hornsby",
      region: "Northern Sydney",
      description:
        "Hornsby Shire includes the Hornsby town centre and surrounding bushland suburbs. Review DA outcomes, environmental considerations, and council behaviour for development in this northern Sydney council area.",
    },
  } as Record<string, { name: string; region: string; description: string }>,
  stats: {
    totalDAs: "Applications Indexed",
    approved: "Approved",
    refused: "Refused",
    deferred: "Deferred",
    approvalRate: "Approval Rate",
  },
  listTitle: (name: string) => `All Development Applications in ${name}`,
  cta: (name: string) => `Scan all ${name} DAs`,
  metaTitle: (name: string) =>
    `${name} Council — DA Approval Risk & Council Behaviour`,
  metaDescription: (name: string, region: string) =>
    `Analyse development application risk in ${name} Council, ${region}. Review approval rates, refusal themes, and consent condition patterns.`,
} as const;

// ── Council Behaviour Snapshot ───────────────────────────────────
export const COUNCIL_SNAPSHOT = {
  title: "Council Behaviour Snapshot",
  approvalRate: "Approval Rate",
  refusalThemes: "Common Refusal Themes",
  consentConditions: "Typical Consent Conditions",
  noData: "Insufficient data for this council area.",
} as const;

// ── Approval Score Gauge Labels ──────────────────────────────────
export const GAUGE = {
  outOf: "out of 100",
  levels: {
    high: { label: "Low Risk — Likely Approved", description: "Strong precedent from similar approved projects" },
    moderate: { label: "Moderate Risk — Uncertain", description: "Mixed signals from comparable developments" },
    low: { label: "High Risk — Likely Refused", description: "Similar projects have mostly been refused" },
  },
} as const;

// ── Navigation ───────────────────────────────────────────────────
export const NAV = {
  links: [
    { href: "/", label: "Overview" },
    { href: "/das", label: "Risk Scan" },
    { href: "/councils/parramatta", label: "Councils" },
  ],
  cta: "Run Risk Scan",
} as const;

// ── PDF Report ───────────────────────────────────────────────────
export const PDF = {
  headerLine1: "DEVELOPMENT APPLICATION",
  headerLine2: "RISK ANALYSIS REPORT",
  footer: "CivroDA — Approval Risk Intelligence",
  approvalScoreLabel: "Approval Risk Score",
  sectionSimilar: "COMPARABLE PRECEDENTS IN COUNCIL AREA",
  sectionScore: "APPROVAL RISK ANALYSIS",
  methodology:
    "Score is calculated using a weighted similarity algorithm comparing zoning (40%), land size (20%), height (20%), and FSR (20%) against precedents within the same council area. This is an indicative score only.",
} as const;

// ── JSON-LD Schema ───────────────────────────────────────────────
export const SCHEMA = {
  home: {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "CivroDA",
    url: "https://civroda.com",
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    description:
      "Approval risk intelligence for Australian property development. Predict DA approval risk, analyse precedents, and review council behaviour patterns.",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "AUD",
    },
    areaServed: {
      "@type": "City",
      name: "Sydney",
      containedInPlace: {
        "@type": "State",
        name: "New South Wales",
      },
    },
  },
} as const;
