import type { DA } from "./types";

export const MOCK_DAS: DA[] = [
  // Parramatta Council (10 records)
  {
    id: "parra-001",
    address: "12 Church Street, Parramatta NSW 2150",
    council: "Parramatta",
    zoning: "B4",
    land_size: "1200 sqm",
    height: "45m",
    FSR: "4:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Must provide minimum 10% communal open space on rooftop",
      "Traffic management plan required prior to construction certificate",
      "Noise attenuation measures for units facing Church Street",
      "Heritage impact statement approved with minor amendments",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-001-determination.pdf",
      "https://council.parramatta.nsw.gov.au/da/parra-001-plans.pdf",
    ],
  },
  {
    id: "parra-002",
    address: "45 Macquarie Street, Parramatta NSW 2150",
    council: "Parramatta",
    zoning: "B4",
    land_size: "980 sqm",
    height: "38m",
    FSR: "3.5:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Basement car parking limited to 120 spaces as per TfNSW guidelines",
      "Affordable housing contribution of 5% of total units required",
      "Stormwater detention system to be installed before occupation certificate",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-002-determination.pdf",
    ],
  },
  {
    id: "parra-003",
    address: "88 Harris Street, Harris Park NSW 2150",
    council: "Parramatta",
    zoning: "R4",
    land_size: "750 sqm",
    height: "24m",
    FSR: "2.5:1",
    DA_outcome: "Refused",
    key_conditions: [
      "Exceeds maximum building height by 3.2 metres — non-compliant with LEP clause 4.3",
      "Insufficient setback from southern boundary causing overshadowing to neighbouring property",
      "Inadequate deep soil landscaping — 8% provided where 15% is required",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-003-refusal.pdf",
    ],
  },
  {
    id: "parra-004",
    address: "5 Fennell Street, North Parramatta NSW 2151",
    council: "Parramatta",
    zoning: "R3",
    land_size: "620 sqm",
    height: "12m",
    FSR: "1.2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Must retain existing mature trees along front boundary",
      "Construction hours limited to 7am–5pm Monday to Saturday",
      "Sewer connection to be upgraded at applicant's cost",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-004-determination.pdf",
    ],
  },
  {
    id: "parra-005",
    address: "220 Victoria Road, Rydalmere NSW 2116",
    council: "Parramatta",
    zoning: "IN1",
    land_size: "3500 sqm",
    height: "15m",
    FSR: "1:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Loading dock access must be from rear lane only",
      "Acoustic barrier required along residential boundary",
      "Hazardous materials management plan to be submitted",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-005-determination.pdf",
    ],
  },
  {
    id: "parra-006",
    address: "33 George Street, Parramatta NSW 2150",
    council: "Parramatta",
    zoning: "B4",
    land_size: "1500 sqm",
    height: "42m",
    FSR: "3.8:1",
    DA_outcome: "Deferred",
    key_conditions: [
      "Additional shadow analysis required for winter solstice impact on Parramatta Square",
      "Revised wind assessment needed — current report does not address ground-level pedestrian comfort",
      "Design review panel recommended facade modifications",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-006-deferral.pdf",
    ],
  },
  {
    id: "parra-007",
    address: "14 Arthur Street, Granville NSW 2142",
    council: "Parramatta",
    zoning: "R2",
    land_size: "450 sqm",
    height: "8.5m",
    FSR: "0.5:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Dual occupancy must maintain minimum 50 sqm private open space per dwelling",
      "Driveway crossover to be widened to 3.5 metres",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-007-determination.pdf",
    ],
  },
  {
    id: "parra-008",
    address: "99 Wigram Street, Harris Park NSW 2150",
    council: "Parramatta",
    zoning: "R4",
    land_size: "820 sqm",
    height: "21m",
    FSR: "2.2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Must provide 15% deep soil landscaping as per DCP",
      "Balconies to include privacy screens on eastern elevation",
      "Section 7.12 contribution of $185,000 payable before construction certificate",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-008-determination.pdf",
    ],
  },
  {
    id: "parra-009",
    address: "7 Station Street East, Parramatta NSW 2150",
    council: "Parramatta",
    zoning: "B2",
    land_size: "580 sqm",
    height: "18m",
    FSR: "2:1",
    DA_outcome: "Refused",
    key_conditions: [
      "Proposed use as residential flat building not permitted in B2 zone",
      "Non-compliance with active street frontage requirement under DCP",
      "Insufficient parking provision for commercial component",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-009-refusal.pdf",
    ],
  },
  {
    id: "parra-010",
    address: "160 Marsden Street, Parramatta NSW 2150",
    council: "Parramatta",
    zoning: "B4",
    land_size: "2200 sqm",
    height: "40m",
    FSR: "3.5:1",
    DA_outcome: "Under Assessment",
    key_conditions: [
      "Awaiting response to heritage referral from Heritage NSW",
      "Traffic study peer review in progress",
    ],
    pdf_links: [
      "https://council.parramatta.nsw.gov.au/da/parra-010-lodgement.pdf",
    ],
  },

  // Blacktown Council (10 records)
  {
    id: "black-001",
    address: "25 Main Street, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "B2",
    land_size: "900 sqm",
    height: "18m",
    FSR: "2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Ground floor must maintain active retail frontage of minimum 80%",
      "Waste management plan required — separate commercial and residential streams",
      "Public domain improvements including footpath widening along Main Street",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-001-determination.pdf",
    ],
  },
  {
    id: "black-002",
    address: "8 Flushcombe Road, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "R3",
    land_size: "700 sqm",
    height: "12m",
    FSR: "1:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Townhouse development limited to 6 dwellings as per lot size",
      "Each dwelling must have minimum 35 sqm private open space",
      "Visitor parking — 2 spaces required in addition to resident allocation",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-002-determination.pdf",
    ],
  },
  {
    id: "black-003",
    address: "142 Richmond Road, Marsden Park NSW 2765",
    council: "Blacktown",
    zoning: "R2",
    land_size: "375 sqm",
    height: "8.5m",
    FSR: "0.55:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Single dwelling compliant with BASIX certificate commitments",
      "Stormwater to be connected to council's drainage system via on-site detention",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-003-determination.pdf",
    ],
  },
  {
    id: "black-004",
    address: "55 Sunnyholt Road, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "B4",
    land_size: "1800 sqm",
    height: "32m",
    FSR: "3:1",
    DA_outcome: "Refused",
    key_conditions: [
      "FSR exceeds maximum permissible 2.5:1 — clause 4.4 variation not supported",
      "Overshadowing of adjacent residential properties exceeds 3-hour midwinter threshold",
      "Inadequate communal open space — 6% provided where 12% required",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-004-refusal.pdf",
    ],
  },
  {
    id: "black-005",
    address: "10 Alpha Street, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "R4",
    land_size: "1100 sqm",
    height: "24m",
    FSR: "2.2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Residential flat building — 32 units approved with 40 car spaces",
      "Landscaping plan must include 3 canopy trees in deep soil zone",
      "Construction traffic management plan to be approved before works commence",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-005-determination.pdf",
    ],
  },
  {
    id: "black-006",
    address: "200 Rooty Hill Road North, Rooty Hill NSW 2766",
    council: "Blacktown",
    zoning: "IN1",
    land_size: "4500 sqm",
    height: "15m",
    FSR: "1:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Industrial warehouse use approved with ancillary office component (max 20% GFA)",
      "Truck movements limited to 20 per day between 7am–6pm",
      "Landscaped buffer of 5 metres required along residential interface",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-006-determination.pdf",
    ],
  },
  {
    id: "black-007",
    address: "77 Patrick Street, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "R3",
    land_size: "650 sqm",
    height: "11m",
    FSR: "0.9:1",
    DA_outcome: "Deferred",
    key_conditions: [
      "Applicant requested to provide revised shadow diagrams for 21 June",
      "Additional acoustic report needed due to proximity to railway corridor",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-007-deferral.pdf",
    ],
  },
  {
    id: "black-008",
    address: "3 Kildare Road, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "R2",
    land_size: "500 sqm",
    height: "8.5m",
    FSR: "0.5:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Granny flat approved — maximum 60 sqm as per SEPP (Affordable Rental Housing)",
      "Must not result in more than 60% hard surface coverage",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-008-determination.pdf",
    ],
  },
  {
    id: "black-009",
    address: "18 Forge Street, Blacktown NSW 2148",
    council: "Blacktown",
    zoning: "B2",
    land_size: "680 sqm",
    height: "15m",
    FSR: "1.8:1",
    DA_outcome: "Refused",
    key_conditions: [
      "Building height exceeds 12m maximum for B2 zone — no exceptional circumstances demonstrated",
      "Car parking shortfall of 8 spaces not supported by transport assessment",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-009-refusal.pdf",
    ],
  },
  {
    id: "black-010",
    address: "400 Richmond Road, Marsden Park NSW 2765",
    council: "Blacktown",
    zoning: "R2",
    land_size: "420 sqm",
    height: "8.5m",
    FSR: "0.6:1",
    DA_outcome: "Under Assessment",
    key_conditions: [
      "Awaiting bushfire assessment report from NSW Rural Fire Service",
      "Biodiversity offset credit calculation pending",
    ],
    pdf_links: [
      "https://council.blacktown.nsw.gov.au/da/black-010-lodgement.pdf",
    ],
  },

  // Hornsby Council (10 records)
  {
    id: "horns-001",
    address: "15 Hunter Street, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "B2",
    land_size: "850 sqm",
    height: "24m",
    FSR: "2.5:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Mixed-use development with ground floor retail and 18 residential units above",
      "Awning required along full Hunter Street frontage for weather protection",
      "Section 7.12 contribution of $220,000 payable before construction certificate",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-001-determination.pdf",
    ],
  },
  {
    id: "horns-002",
    address: "42 Edgeworth David Avenue, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "R4",
    land_size: "950 sqm",
    height: "21m",
    FSR: "2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Residential flat building — 24 units with 30 basement car spaces",
      "Minimum 20% deep soil landscaping required due to bushland proximity",
      "Erosion and sediment control plan required for steep site",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-002-determination.pdf",
    ],
  },
  {
    id: "horns-003",
    address: "8 Dural Lane, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "R2",
    land_size: "680 sqm",
    height: "8.5m",
    FSR: "0.5:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Single dwelling approved — complies with all DCP setback controls",
      "Existing significant tree (Angophora costata) to be retained and protected during construction",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-003-determination.pdf",
    ],
  },
  {
    id: "horns-004",
    address: "120 Pacific Highway, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "B4",
    land_size: "2000 sqm",
    height: "38m",
    FSR: "3.5:1",
    DA_outcome: "Refused",
    key_conditions: [
      "Building envelope exceeds solar access plane — would overshadow Hornsby Mall for more than 4 hours in midwinter",
      "Insufficient separation between tower elements — minimum 18m required, 12m proposed",
      "Traffic generation exceeds capacity of Pacific Highway / George Street intersection",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-004-refusal.pdf",
    ],
  },
  {
    id: "horns-005",
    address: "5 Burdett Street, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "R3",
    land_size: "580 sqm",
    height: "12m",
    FSR: "1:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Townhouse development — 4 dwellings approved",
      "Each dwelling must provide 1 covered car space plus 1 visitor space shared",
      "Boundary fencing to be 1.8m lapped timber along side boundaries",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-005-determination.pdf",
    ],
  },
  {
    id: "horns-006",
    address: "250 Galston Road, Galston NSW 2159",
    council: "Hornsby",
    zoning: "RE1",
    land_size: "5000 sqm",
    height: "9m",
    FSR: "0.3:1",
    DA_outcome: "Refused",
    key_conditions: [
      "Proposed function centre not permitted in RE1 Public Recreation zone",
      "Development would result in clearing of 800 sqm endangered ecological community",
      "Insufficient bushfire asset protection zone",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-006-refusal.pdf",
    ],
  },
  {
    id: "horns-007",
    address: "33 Jersey Street, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "R4",
    land_size: "1050 sqm",
    height: "24m",
    FSR: "2.3:1",
    DA_outcome: "Deferred",
    key_conditions: [
      "Design excellence strategy required under LEP clause 6.8",
      "Applicant to provide revised BCA compliance report addressing fire egress",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-007-deferral.pdf",
    ],
  },
  {
    id: "horns-008",
    address: "90 Peats Ferry Road, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "B2",
    land_size: "720 sqm",
    height: "18m",
    FSR: "2:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Commercial building with 6 retail tenancies approved",
      "End-of-trip cycling facilities required for 20 bicycle spaces",
      "Loading dock to operate between 7am–7pm only",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-008-determination.pdf",
    ],
  },
  {
    id: "horns-009",
    address: "12 Alexandria Parade, Waitara NSW 2077",
    council: "Hornsby",
    zoning: "R3",
    land_size: "550 sqm",
    height: "11m",
    FSR: "0.8:1",
    DA_outcome: "Approved",
    key_conditions: [
      "Dual occupancy with attached garage approved",
      "Stormwater management — OSD tank minimum 5,000 litres",
      "Landscaping to include 2 native canopy trees in front setback",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-009-determination.pdf",
    ],
  },
  {
    id: "horns-010",
    address: "60 George Street, Hornsby NSW 2077",
    council: "Hornsby",
    zoning: "B4",
    land_size: "1600 sqm",
    height: "35m",
    FSR: "3:1",
    DA_outcome: "Under Assessment",
    key_conditions: [
      "Referral to Design Excellence Panel in progress",
      "Transport for NSW concurrence required for Pacific Highway access",
    ],
    pdf_links: [
      "https://council.hornsby.nsw.gov.au/da/horns-010-lodgement.pdf",
    ],
  },
];
